#########################
## Sass Lint File
#########################

# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true

  # Raise an error if more than 50 warnings are generated
  max-warnings: 50


#File Configuration
files:
  ignore:
    - 'styles/scss/login.scss'

# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 0
  no-important: 0
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 0
  single-line-per-selector:
    - 0
  variable-name-format:
    - 0
  no-duplicate-properties:
    - 0
  no-vendor-prefixes:
    - 1
    -
      excluded-identifiers:
        - webkit
        - moz
  nesting-depth:
    - 0
