version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
          JOBS: 1
    steps:
      - checkout
      - run:
          name: yarn
          command: yarn
      - run:
          name: test
          command: yarn test
